//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.8.5.
// MyApp_res.rc

#define IDD_MAINDLG                         100

#define IDR_MAINMENU                        100

#define IDS_REGWNDFAIL                      100
#define IDS_MAKEWNDFAIL                     101

#define ID_EXIT                             100

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    101
        #define _APS_NEXT_COMMAND_VALUE     101
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
